# Generated by Django 4.0.6 on 2025-02-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('codigo_ani', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ani', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AyudaMemoria',
            fields=[
                ('codigo_am', models.BigAutoField(primary_key=True, serialize=False)),
                ('inversion_proyecto_am', models.FloatField(blank=True, null=True)),
                ('inversion_global_am', models.FloatField(blank=True, null=True)),
                ('beneficiarios_am', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion_am', models.TextField(blank=True, null=True)),
                ('lugar_am', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ayuda_memoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Delegado',
            fields=[
                ('codigo_del', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'delegado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('codigo_dir', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_dir', models.CharField(blank=True, max_length=100, null=True)),
                ('color_dir', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('codigo_eve', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado_eve', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo_rechazo_eve', models.CharField(blank=True, max_length=2500, null=True)),
                ('actividad_eve', models.TextField(blank=True, null=True)),
                ('fecha_eve', models.DateTimeField(blank=True, null=True)),
                ('numero_participantes_eve', models.IntegerField(blank=True, null=True)),
                ('duracion_minutos_eve', models.IntegerField(blank=True, null=True)),
                ('lugar_eve', models.CharField(blank=True, max_length=500, null=True)),
                ('latitud_eve', models.FloatField(blank=True, null=True)),
                ('longitud_eve', models.FloatField(blank=True, null=True)),
                ('ubicacion_eve', models.CharField(blank=True, max_length=2500, null=True)),
                ('antecedentes_eve', models.TextField(blank=True, null=True)),
                ('vocativos_eve', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('codigo_mod', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_mod', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'modalidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('codigo_not', models.BigAutoField(primary_key=True, serialize=False)),
                ('mensaje_not', models.CharField(blank=True, max_length=5000, null=True)),
                ('emisor_not', models.BigIntegerField(blank=True, null=True)),
                ('receptor_not', models.BigIntegerField(blank=True, null=True)),
                ('estado_not', models.IntegerField(blank=True, null=True)),
                ('fecha_not', models.DateTimeField(blank=True, null=True)),
                ('codigo_eve', models.BigIntegerField(blank=True, null=True)),
                ('push_not', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjetivoCantonal',
            fields=[
                ('codigo_oc', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion_oc', models.CharField(blank=True, max_length=3500, null=True)),
            ],
            options={
                'db_table': 'objetivo_cantonal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjetivoDesarrollo',
            fields=[
                ('codigo_od', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion_od', models.CharField(blank=True, max_length=3500, null=True)),
            ],
            options={
                'db_table': 'objetivo_desarrollo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjetivoNacional',
            fields=[
                ('codigo_on', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion_on', models.CharField(blank=True, max_length=3500, null=True)),
            ],
            options={
                'db_table': 'objetivo_nacional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjetivoPdyot',
            fields=[
                ('codigo_op', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion_op', models.CharField(blank=True, max_length=3500, null=True)),
            ],
            options={
                'db_table': 'objetivo_pdyot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('codigo_par', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_par', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'parroquia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Poa',
            fields=[
                ('codigo_poa', models.BigAutoField(primary_key=True, serialize=False)),
                ('anio_poa', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_poa', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_dir', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'poa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('codigo_pri', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_pri', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'prioridad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('codigo_pro', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_par', models.BigIntegerField(blank=True, null=True)),
                ('codigo_od', models.BigIntegerField(blank=True, null=True)),
                ('codigo_on', models.BigIntegerField(blank=True, null=True)),
                ('codigo_oc', models.BigIntegerField(blank=True, null=True)),
                ('codigo_op', models.BigIntegerField(blank=True, null=True)),
                ('codigo_poa', models.PositiveBigIntegerField(blank=True, null=True)),
                ('codigo_mod', models.BigIntegerField(blank=True, null=True)),
                ('nombre_pro', models.CharField(blank=True, max_length=5000, null=True)),
                ('descripcion_pro', models.CharField(blank=True, max_length=5000, null=True)),
                ('componentes_pro', models.CharField(blank=True, max_length=5000, null=True)),
                ('total_financiamiento_pro', models.FloatField(blank=True, null=True)),
                ('primer_cuatrimestre_pro', models.IntegerField(blank=True, null=True)),
                ('segundo_cuatrimestre_pro', models.IntegerField(blank=True, null=True)),
                ('tercer_cuatrimestre_pro', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('codigo_tip', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_tip', models.CharField(blank=True, max_length=500, null=True)),
                ('color_tip', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('codigo_uni', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_uni', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_dir', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo_usu', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_usu', models.CharField(blank=True, max_length=100, null=True)),
                ('email_usu', models.CharField(blank=True, max_length=100, null=True)),
                ('password_usu', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_uni', models.BigIntegerField(blank=True, null=True)),
                ('perfil_usu', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_usu', models.IntegerField(blank=True, null=True)),
                ('es_delegado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vocativo',
            fields=[
                ('codigo_voc', models.BigAutoField(primary_key=True, serialize=False)),
                ('apellido_voc', models.CharField(blank=True, max_length=500, null=True)),
                ('nombre_voc', models.CharField(blank=True, max_length=500, null=True)),
                ('cargo_voc', models.CharField(blank=True, max_length=500, null=True)),
                ('telefono_voc', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'vocativo',
                'managed': False,
            },
        ),
    ]
