from django.contrib import admin
from.models import *

admin.site.register(Anio)
admin.site.register(AyudaMemoria)
admin.site.register(Delegado)
admin.site.register(Direccion)
admin.site.register(Evento)
admin.site.register(Modalidad)
admin.site.register(Notificacion)
admin.site.register(ObjetivoCantonal)
admin.site.register(ObjetivoDesarrollo)
admin.site.register(ObjetivoNacional)
admin.site.register(ObjetivoPdyot)
admin.site.register(Parroquia)
admin.site.register(Poa)
admin.site.register(Prioridad)
admin.site.register(Proyecto)
admin.site.register(Tipo)
admin.site.register(Unidad)
admin.site.register(Usuario)
admin.site.register(Vocativo)
